name: App Simples

deploys:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: deploy via ssh (appleboy)
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        scripts: |
          cd ~
          if [ ! -d "danilo.app" ]; then
            git clone https://github.com/${{ github.repository }} danilo-app
            fi
            cd danilo-app
            git pull origin main
            docker compose pull
            docker compose up -d
